name: Atualizar dados das praias

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4 pandas lxml

      - name: Executar script
        run: |
          python gerar_json_praias.py

    - name: Commit e push seguro
      run: |
        git config --global user.name "bot-to-de-onda"
        git config --global user.email "bot@github.com"
    
        # garante que estamos na branch main atualizada
        git fetch origin
        git checkout main
        git reset --hard origin/main
    
        # adiciona mudanças
        git add praias_rj.json
    
        # commit (se houver mudança)
        git commit -m "Atualização automática das praias" || echo "Sem mudanças"
    
        # push forçado seguro
        git push origin main
